FROM python:3.10.11-slim
WORKDIR /usr/local/app

# Install the application dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy in the source code
COPY main.py ./
COPY serverModelUse.py ./
EXPOSE 8080

# Install wget and curl for downloading
RUN apt-get update && apt-get install -y wget curl

# Download the model file
RUN mkdir -p model && \
    wget -O model/disaster_classifierV2.pt "https://www.dropbox.com/scl/fi/t1sdn6zzff9x7l492viir/disaster_classifierV2.pt?rlkey=utk7th4fdki948w9bff4m8tkq&st=fmkdtupd&dl=1"

# Setup an app user so the container doesn't run as the root user
RUN useradd app
USER app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]