FROM python:3.10.11-slim
WORKDIR /usr/local/app

# Install the application dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy in the source code
COPY main.py ./
COPY serverModelUse.py ./
EXPOSE 8080

# Install wget and curl for downloading
RUN apt-get update && apt-get install -y wget curl

# Download the model file
RUN mkdir -p model && \
    wget -O model/disaster_classifierV5.pt "https://www.dropbox.com/scl/fi/jgnqwxlnss6ax30lo8vng/disaster_classifierV5.pt?rlkey=nkwbresdp6wjo4rdmkfn65pe2&st=d7fcbvj6&dl=1"

# Setup an app user so the container doesn't run as the root user
RUN useradd app
USER app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]